Childcare/Controllers/ChildDayController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Childcare.Models;

namespace Childcare.Controllers
{
    public class ChildDayController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ChildDay
        public ActionResult Index()
        {
            var childDays = db.ChildDays.Include(c => c.Child);
            
            return View(childDays.ToList());
        }

        // GET: ChildDay/Details/5
        public ActionResult Details(short? id, string day)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Days dayno = (Days)Enum.Parse(typeof(Days), day, true);

            ChildDay childDay = db.ChildDays.Find(id, dayno);

            if (childDay == null)
            {
                return HttpNotFound();
            }
            return View(childDay);
        }

        // GET: ChildDay/Create
        public ActionResult Create()
        {
            ViewBag.childid = new SelectList(db.Children, "childid", "childname");
            return View();
        }

        // POST: ChildDay/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "childid,Day")] ChildDay childDay)
        {
            if (ModelState.IsValid)
            {
                db.ChildDays.Add(childDay);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.childid = new SelectList(db.Children, "childid", "childname", childDay.childid);
            return View(childDay);
        }

        // GET: ChildDay/Edit/5
        public ActionResult Edit(short? id, string day)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Days dayno  = (Days)Enum.Parse(typeof(Days), day, true);
        
            ChildDay childDay = db.ChildDays.Find(id, dayno);
            if (childDay == null)
            {
                return HttpNotFound();
            }
            ViewBag.childid = new SelectList(db.Children, "childid", "childname", childDay.childid);
            return View(childDay);
        }

        // POST: ChildDay/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "childid,Day")] ChildDay childDay)
        {
            if (ModelState.IsValid)
            {
                db.Entry(childDay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.childid = new SelectList(db.Children, "childid", "childname", childDay.childid);
            return View(childDay);
        }

        // GET: ChildDay/Delete/5
        public ActionResult Delete(short? id, string day)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Days dayno = (Days)Enum.Parse(typeof(Days), day, true);
            ChildDay childDay = db.ChildDays.Find(id, dayno);
            if (childDay == null)
            {
                return HttpNotFound();
            }
            return View(childDay);
        }

        // POST: ChildDay/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id, string day)
        {
            Days dayno = (Days)Enum.Parse(typeof(Days), day, true);
            ChildDay childDay = db.ChildDays.Find(id, dayno);
            db.ChildDays.Remove(childDay);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Childcare/Controllers/ChildGuardianController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Childcare.Models;

namespace Childcare.Controllers
{
    public class ChildGuardianController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ChildGuardian
        public ActionResult Index()
        {
            var childGuardians = db.ChildGuardians.Include(c => c.Child).Include(c => c.Guardian).OrderBy(c=>c.childid).ThenByDescending(c=>c.Guardian.guardianrelationship);
            return View(childGuardians.ToList());
        }

        // GET: ChildGuardian/Details/5
        public ActionResult Details(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChildGuardian childGuardian = db.ChildGuardians.Find(id);
            if (childGuardian == null)
            {
                return HttpNotFound();
            }
            return View(childGuardian);
        }

        // GET: ChildGuardian/Create
        public ActionResult Create()
        {
            ViewBag.childid = new SelectList(db.Children, "childid", "childname");
            ViewBag.guardianid = new SelectList(db.Guardians, "guardianid", "guardianname");
            return View();
        }

        // POST: ChildGuardian/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "childid,guardianid")] ChildGuardian childGuardian)
        {
            if (ModelState.IsValid)
            {
                db.ChildGuardians.Add(childGuardian);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.childid = new SelectList(db.Children, "childid", "childname", childGuardian.childid);
            ViewBag.guardianid = new SelectList(db.Guardians, "guardianid", "guardianname", childGuardian.guardianid);
            return View(childGuardian);
        }

        // GET: ChildGuardian/Edit/5
        public ActionResult Edit(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChildGuardian childGuardian = db.ChildGuardians.Find(id);
            if (childGuardian == null)
            {
                return HttpNotFound();
            }
            ViewBag.childid = new SelectList(db.Children, "childid", "childname", childGuardian.childid);
            ViewBag.guardianid = new SelectList(db.Guardians, "guardianid", "guardianname", childGuardian.guardianid);
            return View(childGuardian);
        }

        // POST: ChildGuardian/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "childid,guardianid")] ChildGuardian childGuardian)
        {
            if (ModelState.IsValid)
            {
                db.Entry(childGuardian).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.childid = new SelectList(db.Children, "childid", "childname", childGuardian.childid);
            ViewBag.guardianid = new SelectList(db.Guardians, "guardianid", "guardianname", childGuardian.guardianid);
            return View(childGuardian);
        }

        // GET: ChildGuardian/Delete/5
        public ActionResult Delete(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChildGuardian childGuardian = db.ChildGuardians.Find(id);
            if (childGuardian == null)
            {
                return HttpNotFound();
            }
            return View(childGuardian);
        }

        // POST: ChildGuardian/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            ChildGuardian childGuardian = db.ChildGuardians.Find(id);
            db.ChildGuardians.Remove(childGuardian);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ChildGuardians()
        {
            //var childguardians = db.ChildGuardians.Include(c => c.Child).Include(c => c.Guardian).OrderBy(c => c.childid);
            //return View(childguardians.ToList());

            IEnumerable<ChildGuardian> childguardian = (from cg in db.ChildGuardians
                                                        join ch in db.Children on cg.childid equals ch.childid
                                                        join c in db.Guardians on cg.guardianid equals c.guardianid
                                                        select new { cg, ch, c }) as IEnumerable<ChildGuardian>;
            return View(childguardian);
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Childcare/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Childcare.Models;

namespace Childcare.Controllers
{
    public class EnrollmentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Enrollment
        public ActionResult Index()
        {
            var enrollments = db.Enrollments.Include(e => e.Child);
            return View(enrollments.ToList());
        }

        // GET: Enrollment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollment/Create
        public ActionResult Create()
        {
            ViewBag.childid = new SelectList(db.Children, "childid", "childname");
            return View();
        }

        // POST: Enrollment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "enrollmentid,enrollmentdate,enrollmentfrom,enrollmentto,childid")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.Add(enrollment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.childid = new SelectList(db.Children, "childid", "childname", enrollment.childid);
            return View(enrollment);
        }

        // GET: Enrollment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            ViewBag.childid = new SelectList(db.Children, "childid", "childname", enrollment.childid);
            return View(enrollment);
        }

        // POST: Enrollment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "enrollmentid,enrollmentdate,enrollmentfrom,enrollmentto,childid")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.childid = new SelectList(db.Children, "childid", "childname", enrollment.childid);
            return View(enrollment);
        }

        // GET: Enrollment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enrollment enrollment = db.Enrollments.Find(id);
            db.Enrollments.Remove(enrollment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Childcare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
   @{
       Html.RenderPartial("_myPartialView");
}
    <div class="container body-content">
        @RenderBody()
        <hr />
        @if (IsSectionDefined("mysection1"))
        {
            @RenderSection("mysection", true);
        }



        <footer>
            @{
                Html.RenderPartial("_PartialFooterView");
            }
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
   
</body>
</html>

Childcare/Views/Shared/_PartialFooterView.cshtml
<div>
    
    <p>&copy; @DateTime.Now - My ASP.NET Application</p>
   
</div>

Childcare/Views/Shared/_myLayout.cshtml
@{
    ViewBag.Title = "Home Page";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")

</head>
@{
    Html.RenderPartial("_myPartialView");
}
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-3">
        <body>
           
            <div class="container body-content">
                @RenderBody()
                <hr />
                @if (IsSectionDefined("mysection1"))
                {
                    @RenderSection("mysection", true);
                }


            </div>
     </div>
            <div class="col-md-6">
                <h2>Getting started</h2>
                <p>
                    ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                    enables a clean separation of concerns and gives you full control over markup
                    for enjoyable, agile development.
                </p>
                <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
            </div>
            <div class="col-md-3">
                <footer>
                    @{
                        Html.RenderPartial("_PartialFooterView");
                    }
                </footer>
            </div>
            
            @*section footer{
                    <p class="lead">
                        This is footer section.
                    </p>
                }*@
    </div>

Childcare/Views/Shared/_myLayoutPage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
   
    @{
        Html.RenderPartial("_myPartialView");
    }
       
    <div>
        @RenderBody()
    </div>
    <footer class="panel-footer">
        @*RenderSection("footer", true)*@
        @{
            Html.RenderPartial("_PartialFooterView");
        }
    </footer>
</body>
</html>

Childcare/Views/Shared/_myPartialView.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div>
        <img class="img-circle" src="--/content/images/childcare01.jpg" width="250" height="100" />
            </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Child", "Create", "Child")</li>
                <li>@Html.ActionLink("Guardian", "Create", "Guardian")</li>
                <li>@Html.ActionLink("Child->Enrollment", "Create", "Enrollment")</li>
                <li>@Html.ActionLink("Child<->Payment", "Create", "ChildPayment")</li>
                <li>@Html.ActionLink("Child<->Guardian", "Index", "ChildGuardian")</li>
                <li>@Html.ActionLink("Child<->Day", "Create", "ChildDay")</li>
                <li>@Html.ActionLink("About Us", "About", "Home")</li>
                <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>